### PR TITLE
Update to 7.5

### PR DESCRIPTION
**Pull request by TechnologyClassroom**

### CODE REVIEW

**Comment by sdoconnell** [comment]
Just to confirm, you've verified that ELLIS works properly with CentOS 7.5 and no regressions?

**Comment by TechnologyClassroom** [comment]
I have not tested the script yet.  I noticed that the script will fail to run following the Setup and Installation steps because step 2 ```yum -y update``` will always upgrade to 7.5 now.  Maybe a check to see if it is greater than or equal to 7.3 would be more future proof.

**Comment by sdoconnell** [comment]
I put the version check in the script for two reasons: a) sometimes things do change with the package configurations from minor version to minor version (which caused a minor break with LDAP I think in a previous version), and b) to reduce bug reports from people running CentOS versions other than the supported one (which I've always maintained is the current version - I just haven't had inclination to test against 7.4-7.5 and update the script - bad me).

I'd really rather not do a ">=7.3" type of thing as I just don't have time to bug test against multiple versions. For those who want or need to run a different version of CentOS on the host, there is always the option to override the version check (uncomment CHECKVER=false) and use an "unsupported" version. Which should work fine for regression testing against 7.5, also.

By the way, the KERNUPDURL variable will also need to be changed for CentOS 7.5 to:

    KERNUPDURL="http://mirror.centos.org/centos-7/7/updates/x86_64/Packages/kernel-3.10.0-862.3.3.el7.x86_64.rpm"

so that the kernel repo gets a version newer than the released version in CentOS 7.5 (build 1804). (The lab VMs themselves should not be `yum -y update`'d after they are built).

Regarding 7.5, I'd be happy to update the script with the needed changes I just want to make sure it is tested thoroughly prior. If you have the time to do the testing, that would be awesome. Otherwise I'll try to find a chance this week to do that and push the changes (I'll add merge this PR when I do). Thanks.

**Comment by TechnologyClassroom** [comment]
That makes sense.  I am testing in a VM with the KERNUPDURL.  I will check on it tomorrow.

**Comment by TechnologyClassroom** [comment]
When I came in this morning, the script had completed and elinks was open with a message.

2018-06-19-092640_1920x1080_scrot

I am unfamiliar with elinks and I am not sure if that is regular behavior.

I tested under VirtualBox with NAT and CentOS 7.5 minimal.  I cannot test with bare metal on my work network.

**Comment by sdoconnell** [comment]
Thanks, that doesn't really tell me much though. I'll have to run on it on lab machine here, check all units configured properly, etc. I may find time for that tomorrow. I'll update after I run my tests.

**Comment by sdoconnell** [comment]
Closing this PR. The update is done and tested. It was more than just changing the CHECKVER.

**Comment by TechnologyClassroom** [comment]
The new variables section is well organized.  Nice script!

**Pull request closed without merging**
